name: Chart Test

on:
  pull_request:
    branches: [master, main]

env:
  KUBERNETES_VERSION: "1.27.1"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

        # Default yaml styles
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: .
          config_file: .yamllint.yaml

        # Chart testing
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Validate Helm Chart
        uses: docker://ghcr.io/wdaan/helm-kubeconform-action:v0.1.7
        env:
          ADDITIONAL_SCHEMA_PATHS: |
            schemas/{{ .ResourceKind }}.json
          CHARTS_DIRECTORY: "examples"
          KUBECONFORM_STRICT: "true"
          HELM_UPDATE_DEPENDENCIES: "true"
          IGNORE_MISSING_SCHEMAS: "true"
          KUBERNETES_VERSION: ${{ env.KUBERNETES_VERSION }}
          LOG_JSON: "false"
