name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  packages: write

env:
  REGISTRY: ghcr.io/${{ github.repository }}
  HELM_VERSION: 3.11.0
  HELM_EXPERIMENTAL_OCI: 1

jobs:
  setup-release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: helm
          package-name: common-chart 
  
  release:
    needs: setup-release
    if: ${{ needs.setup-release.outputs.release_created }}
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@master
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: ${{ env.HELM_VERSION }}
      - name: Helm Login
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ${{ env.REGISTRY }} --username ${{ github.actor }} --password-stdin
      - name: Helm Package && Publish
        run: |
          helm package common
          helm push common.tgz oci://ghcr.io/${{ env.ORG }}/common-chart

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GH_TOKEN }}"
          prerelease: false
          files: |
            README.md
            *.tgz
