name: Release

on:
  release:

permissions:
  contents: write
  pull-requests: write
  packages: write

env:
  REGISTRY: ghcr.io/${{ github.repository }}
  HELM_VERSION: 3.11.3
  HELM_EXPERIMENTAL_OCI: 1

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: ${{ env.HELM_VERSION }}
      - name: Helm Login
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ${{ env.REGISTRY }} --username ${{ github.actor }} --password-stdin
      
      - name: Helm Package && Publish
        run: |
          helm package charts/base
          helm push base-*.tgz oci://ghcr.io/wdaan/base-chart
      
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
